apiVersion: v1                  # 디스크립터는 쿠버네티스 API 버전v1을 준수함
kind: Pod                       # 객체의 종류가 Pod임
metadata:
  name: kubia-manual            # 파드 이름
spec:
  containers:
    - image:                    # 컨테이너를 만드는 컨테이너 이미지
      name: kubia               # 컨테이너 이름
      ports:
      - containerPort: 9090     # 애플리케이션을 수신하는 포트
        protocol: TCP
